# For some reason, I need to release the red button right before doing
# the upload, or it doesn't take.
# http://www.arduino.cc/en/Guide/ArduinoLeonardoMicro?from=Guide.ArduinoLeonardo#toc12

BOARD_TAG    = leonardo
MONITOR_PORT = $(shell ls /dev/ttyACM*)
ARDUINO_LIBS =
#AVRDUDE_OPTS = -V -D -v -v -v -v

include /usr/share/arduino/Arduino.mk
